hideManual: true
watch:
  directories:
    - src
    - tests
    - pages
  fileMask: "*.php"
notifications:
  passingTests: false
  failingTests: false
phpunit:
  binaryPath: vendor/bin/phpunit
  arguments: "--stop-on-failure"
  timeout: 180
